[console]

sinkType = Sync
level = Info
colorMode = Ansi

[console.component.levels]

# e.g. to log more verbose messages about the 'net' component, uncomment
# net = Debug

[file]

sinkType = Async
level = Info
directory = /home/igor/projects/proximax-sirius-core/chainconfig/logs
filePattern = /home/igor/projects/proximax-sirius-core/chainconfig/logs/recovery_%4N.log
rotationSize = 25MB
maxTotalSize = 250MB
minFreeSpace = 100MB

[file.component.levels]